# Site settings
title: Manz Are Getting Married.com
email: shim.bindra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to Manz Are Getting Married.com! This should give you the info you need for Shim and Manpreet’s big day.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://shimbindra.github.io"
#url: "http://localhost:4000"
twitter_username: shimmi_b
github_username:  shimbindra

# Build settings
markdown: kramdown
